services:
  todo_api_app_dev:
    container_name: the_template
    image: the_template:1.0.0
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production