services:
  webapi:
    image: ghcr.io/${GITHUB_USER_NAME}/${IMAGE_NAME}:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - urls=http://0.0.0.0:8080
      - S3AwsSettings_AccessKey=BMy2mJX8IXXqmwwn5ucN
      - S3AwsSettings_SecretKey=GEeZxE8rTKcTcwOJ3Y3tdFNDqx9iVI9YhOgLhrRP
    expose:
      - "8080"
    networks:
      - the-template-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  the-template-network:
    external: true
